export const SET_SLIDES = "SET_SLIDES";
export const FETCHING_API = "FETCHING_API";
export const FETCHING_API_SUCCESS = "FETCHING_API_SUCCESS";
export const FETCHING_API_FAILED = "FETCHING_API_FAILED";
