// export const SET_PRESENTATION = "SET_PRESENTATION";
// export const SET_SLIDES = "SET_SLIDES";
// export const FETCHING_API = "FETCHING_API";
// export const FETCHING_API_SUCCESS = "FETCHING_API_SUCCESS";
// export const FETCHING_API_FAILED = "FETCHING_API_FAILED";
// export const SET_INIT = "SET_INIT";
// export const CHECK_LOAD_NEW_DATA = "CHECK_LOAD_NEW_DATA";

// export const SET_PRESENTATION_TYPES_CONFIG = "SET_PRESENTATION_TYPES_CONFIG";
// export const SET_PRESENTATION_THEMES_CONFIG = "SET_PRESENTATION_THEMES_CONFIG";
// export const SET_SLIDE_TYPES_CONFIG = "SET_SLIDE_TYPES_CONFIG";
