export const PRESENTATION_ACTION = Object.freeze({
   SET_COUNT_SLIDE: "SET_COUNT_SLIDE",
   SET_ORDINAL_SLIDE_NUMBER: "SET_ORDINAL_SLIDE_NUMBER",
   SET_JOIN_HOST: "SET_JOIN_HOST",
   SET_SLIDE: "SET_SLIDE"
});
