export const SET_PRESENTATION = "SET_PRESENTATION";
export const SET_SLIDES = "SET_SLIDES";
export const FETCHING_API = "FETCHING_API";
export const FETCHING_API_SUCCESS = "FETCHING_API_SUCCESS";
export const FETCHING_API_FAILED = "FETCHING_API_FAILED";
export const SET_INIT = "SET_INIT";
export const CHECK_LOAD_NEW_DATA = "CHECK_LOAD_NEW_DATA";
