export const SET_PRESENTATION = "SET_PRESENTATION";
export const SET_CURRENT_SLIDE = "SET_CURRENT_SLIDE";
export const SET_CURRENT_SLIDE_INDEX = "SET_CURRENT_SLIDE_INDEX";
export const FETCHING_API = "FETCHING_API";
export const FETCHING_API_SUCCESS = "FETCHING_API_SUCCESS";
export const FETCHING_API_FAILED = "FETCHING_API_FAILED";
